Add a sniff to fix duplicate full stops in comments
pfrenssen/coder pull request #101
Opened 2020-04-11 17:24 UTC by jungleran

https://www.drupal.org/project/coder/issues/3126860

2020-05-08 10:04 UTC, klausi reviewed
I think this sniff is not fully sufficient since it does not take comment paragraphs into account. Example:

```
// This is an example comment where I will demonstrate the usage of path ./../..
// in this sentence.
```

So I think we need to integrate this into our existing comment sniffs that check if a comment ends with a dot. DocCommentSniff, FunctionCommentSniff and InlineCommentSniff I think.

2020-05-08 10:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/Commenting/DuplicateFullStopSniff.php
> +            if ($phpcsFile->fixer !== null) {
please use the return value of addFixableWarning() to check if the fixer is enabled like we do in other sniffs.

2020-05-08 10:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/Commenting/DuplicateFullStopSniff.php
> +                $contentReversed = strrev($content);
why this complicated fix? Can we use strrpos() for ".." and then assemble the replacement with substr() and only add one dot?

2020-05-16 08:40 UTC, klausi requested changes
Requesting changes per comment above.

2020-05-16 09:58 UTC, jungleran commented
Hi @klausi,  I will work on it in hours, thanks for your review!

2020-05-17 12:03 UTC, ranqiangjun reviewed
Self-review

2020-05-17 12:03 UTC, jungleran commented on tests/Drupal/Commenting/InlineCommentUnitTest.inc.fixed
> +// in this sentence.
Addressed the example.

2020-05-17 12:03 UTC, jungleran commented on coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php
> +            // Ignore ... and /.. .
Ignore comments end with three dots and comments look like a path. `/..`

2020-05-17 12:04 UTC, jungleran commented on coder_sniffer/Drupal/Sniffs/Commenting/DuplicateFullStopSniff.php
> +            if ($phpcsFile->fixer !== null) {
Did in this iteration.

2020-05-17 12:07 UTC, jungleran commented on coder_sniffer/Drupal/Sniffs/Commenting/DuplicateFullStopSniff.php
> +                $contentReversed = strrev($content);
Here is for ignoring comments end with `...`, simplified a little in this/the new iteration

2020-05-17 12:09 UTC, jungleran commented
It's an incomplete one, will continue when I get time. Only touched DocCommentSniff and InlineCommentSniff so far.

2021-12-25 16:44 UTC, klausi commented
Closing this pull request due to inactivity, please open a new one if you are working on this again!

2021-12-25 16:44 UTC, closed without merging