Detect conflicts between FQN classes and declared classes.
pfrenssen/coder pull request #109
Opened 2020-06-03 12:48 UTC by cburschka

Fixing https://www.drupal.org/project/coder/issues/3137489

2020-06-03 13:47 UTC, cburschka commented
(I'm not sure why the CI seems to be stuck at reporting back the build status)

2020-06-03 16:07 UTC, arkener requested changes
Looks good to me, just 2 minor things and then we can merge this. We should also add an extra test for this use-case on FullyQualifiedNamespaceUnitTest.

2020-06-03 16:07 UTC, arkener commented on coder_sniffer/Drupal/Sniffs/Classes/FullyQualifiedNamespaceSniff.php
> +                $declaredName = $phpcsFile->getTokensAsString($afterClassStatement, 1);
The token content `$tokens[$afterClassStatement]['content']` can be used to determine the class name.

2020-06-03 16:07 UTC, Arkener commented on coder_sniffer/Drupal/Sniffs/Classes/FullyQualifiedNamespaceSniff.php
> +        while ($classStatement !== false) {
We should probably skip this conflict check if we already received a $conflict earlier in this sniff.

2020-06-03 16:09 UTC, Arkener commented
Not really sure why Travis isn't reporting the status here, but the [tests](https://travis-ci.org/github/pfrenssen/coder/builds/694241406) are completed successfully.

2020-06-03 16:27 UTC, cburschka commented on coder_sniffer/Drupal/Sniffs/Classes/FullyQualifiedNamespaceSniff.php
> +                $declaredName = $phpcsFile->getTokensAsString($afterClassStatement, 1);
Ah, thanks for pointing that out.

2020-06-03 17:06 UTC, cburschka commented
Hadn't noticed I was working on an old branch; merging 8.x-3.x.

2020-06-04 08:46 UTC, arkener approved these changes

2020-06-04 08:52 UTC, merged

2020-06-04 08:55 UTC, Arkener commented
Looks good, merged, thanks!