Add UseGlobalClassSniff.
pfrenssen/coder pull request #110
Opened 2020-06-03 13:46 UTC by cburschka

Adds a sniff for global class imports. https://www.drupal.org/project/coder/issues/3120001

2020-06-04 10:27 UTC, cburschka commented
Fixed the bug that removed function imports, and a quirk that left blank lines between use statements (unlike extra blank lines before and after the block, these are currently not removed by other sniffs). Unit test expanded to cover that.

2020-06-05 09:12 UTC, klausi requested changes
Nice work, thank you!

I just have 2 minor comments, then I think we can merge this.

I briefly researched if there is already a sniff in upstream PHPCS but could not find anything. So I think it is ok that we invent a sniff here for now that really the whole PHP community would want otherwise.

2020-06-05 09:12 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/Classes/UseGlobalClassSniff.php
> +            $phpcsFile->fixer->beginChangeset();
the fixer should only run if the return value of addFixableError() is true. You can check that in other classes that implement a fixer.

2020-06-05 09:12 UTC, klausi commented on tests/Drupal/Classes/UseGlobalClassUnitTest.php
> +    protected function getTestFiles($testFileBase): array
this method can be removed, the default implementation will pick up the test file by the same name

2020-06-05 10:50 UTC, cburschka commented on coder_sniffer/Drupal/Sniffs/Classes/UseGlobalClassSniff.php
> +            $phpcsFile->fixer->beginChangeset();
Thanks! I'd only checked the FullyQualifiedNamespace sniff, and assumed the condition there was just for checking whether the error was fixable (which it always is here), not that the fixer is enabled as well.

2020-06-05 14:18 UTC, merged