Use vendor/sirbrillig/phpcs-variable-analysis
pfrenssen/coder pull request #111
Opened 2020-06-06 12:13 UTC by alexpott

See https://www.drupal.org/project/coder/issues/3147228

2020-06-06 12:14 UTC, alexpott commented on coder_sniffer/DrupalPractice/ruleset.xml
> +  <rule ref="vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php">
This is ugly. What's the right way to do this?

2020-06-06 13:42 UTC, alexpott commented on coder_sniffer/DrupalPractice/ruleset.xml
> +  <rule ref="vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php">
I've changed this in the latest PR to add the old DrupalPractice sniff back but only as a class that extends the vendor class. This seems to work quite well.

2020-06-06 15:44 UTC, arkener requested changes
Thanks for your work on this!, I've added some minor remarks and left a [comment](https://www.drupal.org/project/coder/issues/3119378#comment-13671680) on the Drupal.org issue in regards to this issue.

2020-06-06 15:44 UTC, Arkener commented on coder_sniffer/DrupalPractice/ruleset.xml
> +      <property name="allowUnusedFunctionParameters" value="1"/>
Boolean values should be specified by using the strings "true" and "false" rather than the integers 0 and 1.

2020-06-06 15:44 UTC, Arkener commented on tests/DrupalPractice/CodeAnalysis/VariableAnalysisUnitTest.inc
> +    $names[$i] = $event_name;
We should use 2 space indentation for this testfile.

2020-06-09 20:57 UTC, arkener approved these changes
Thanks!, everything seems good to go.

2020-06-09 20:58 UTC, merged