tests(phpstan): Remove ignored rules that have been fixed in PHPStan and remove unused code
pfrenssen/coder pull request #126
Opened 2020-10-24 18:42 UTC by Arkener

2020-10-25 10:20 UTC, jonathan1055 commented
Is this for fixing these latest phpstan test failures in Travis?
````
  Ignored error pattern #^Result of && is always false\.$# 
````

2020-10-25 10:55 UTC, Arkener commented
Ah, forgot to add the description. This PR removes the following ignored rules and "fixes" an newly triggered error on FunctionCommentSniff:241, which was triggered on an unused if statement. These ignored rules have been fixed upstream in PHPStan 0.12.51
------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php                                                                                                                                                                                                  
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
         Ignored error pattern #^Result of && is always false\.$# in path /usr/share/nginx/html/indicia/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php was not matched in reported errors.                                                         
         Ignored error pattern #^Strict comparison using \=\=\= between true and false will always evaluate to false\.$# in path /usr/share/nginx/html/indicia/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php was not matched in reported errors.  
         Ignored error pattern ~^Variable \$fileShort in isset\(\) always exists and is not nullable.$~ in path /usr/share/nginx/html/indicia/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php was not matched in reported errors.                   
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   coder_sniffer/Drupal/Sniffs/Commenting/FunctionCommentSniff.php                                                                                                                                                                                   
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
         Ignored error pattern #^Else branch is unreachable because previous condition is always true\.$# in path /usr/share/nginx/html/indicia/coder/coder_sniffer/Drupal/Sniffs/Commenting/FunctionCommentSniff.php was not matched in reported errors.  
         241 | Comparison operation ">" between int<1, max> and 0 is always true.                                                                                                                                                                                
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2020-11-04 11:14 UTC, klausi requested changes
Nice, thank you! All looking good, we should just remove the now obsolete comment in the phstan config.

2020-11-04 11:14 UTC, klausi commented on phpstan.neon
>          # nullable. https://github.com/phpstan/phpstan/issues/2816
this comment now also needs to be removed.

2020-11-04 11:56 UTC, klausi commented
I will fix that in a small follow-up commit.

2020-11-04 11:56 UTC, merged