Issue #3271952: Validate function names are prefixed with module name.
pfrenssen/coder pull request #161
Opened 2022-04-11 13:39 UTC by vbouchet31

https://www.drupal.org/project/coder/issues/3271952

2022-05-08 09:04 UTC, klausi requested changes
Thanks, the approach make sense! I have some minor comments to improve test coverage and output, then I think we can go ahead with this.

2022-05-08 09:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> +    protected $functionPrefixes = ['template_preprocess'];
for Drupal 7 we also need to allow the prefix "theme" (and "phptemplate", probably not that relevant anymore. See https://git.drupalcode.org/project/pareviewsh/-/blob/7.x-1.x/pareview.sh#L285

Let's add a test case for this in a *.module file for the ValidFunctionNameUnitTest

2022-05-08 09:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> +                $phpcsFile->addError($error, $stackPtr, 'InvalidName', $data);
let's use a new error code here instead of 'InvalidName', so that people can make targeted exceptions for this in their configurations. I would suggest to use "InvalidPrefix".

2022-05-08 09:04 UTC, klausi commented on tests/Drupal/bad/bad.module
> +function not_respecting_naming_convention_with_module_prefix() {
Let's move this to the ValidFunctionNameUnitTest directory and make a *.module file there.

2022-05-08 09:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> +        $nameParts     = explode('.', basename($phpcsFile->getFilename()));
let's use the same approach as with *.api.php files above with substr().

2022-05-08 09:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> +    protected $functionPrefixes = ['template_preprocess'];
Let's rename this to "allowedFunctionPrefixes"

2022-05-08 09:04 UTC, klausi commented on coder_sniffer/Drupal/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> +                $error = 'All functions defined in a module file must be prefixed with the module\'s name, found "%s".';
We should give an example what we expect like "All functions defined in a module file must be prefixed with the module\'s name, found "%s" but expected "%s"". For the expected name we can just prefix the function name with `$moduleName . '_'`

2022-05-10 10:01 UTC, vbouchet31 commented
Thanks for the review @klausi . I updated the PR.

2022-05-10 10:12 UTC, merged