Test for regressions against Drupal core
pfrenssen/coder pull request #207
Opened 2023-07-16 10:52 UTC by Boegie

See https://www.drupal.org/project/coder/issues/3374864

2023-07-16 10:59 UTC, Boegie commented
So now we know, as expected/wanted, the current HEAD of `drupal/coder` returns no errors when running the Drupal coding standards against Drupal core HEAD.

We also want to know:

- If the test runs correctly, not only when creating a PR but also when doing "just" a commit.
- if the test fails on a recent regression.

Let's revert "Fix regression in 8.3.19 for variadic function parameters (#3365993)" to test both,

2023-07-16 11:04 UTC, Boegie commented
Good enough for me, let's revert the revert to have only the addition of the new GitHub CI step in this PR,

2023-07-16 21:40 UTC, jonathan1055 commented
NIce work. One question about the failed test
![test against core](https://github.com/pfrenssen/coder/assets/19403539/f6d10132-2d1a-49b7-a4a0-68be33df9689)

2023-07-17 04:39 UTC, Boegie commented
Nice catch.

Should be fixed now.

Fail test showing the fail:
![image](https://github.com/pfrenssen/coder/assets/18569707/1b1cc20c-bbd5-4ab4-86a8-bb67b596c81c)

Including failed mail:
![image](https://github.com/pfrenssen/coder/assets/18569707/f443984e-f49a-45f6-a4e8-995aedc62053)

2023-07-17 07:20 UTC, jonathan1055 commented
Excellent.

2023-07-17 07:29 UTC, jonathan1055 commented
This will only detect regressions in the sniffs that core has enabled, so there could be things that still get missed. It's good to see that in recent months there has been a push to get more sniffs passing and enabled in core. Here's the current list of things being worked on https://www.drupal.org/project/drupal/issues/2571965

2023-07-17 07:34 UTC, jonathan1055 commented
For example, the regression in [constantName.constantStart](https://www.drupal.org/project/coder/issues/3369978) would not have been discovered because Core has not enabled this rule yet.

2023-07-17 07:50 UTC, Boegie commented
> This will only detect regressions in the sniffs that core has enabled, so there could be things that still get missed.

AFAIK, that's exactly why new stuff goes into new rules and it should be a core queue issue to fix new failures on the new rule before enabling it (in the same issue) in `core/phpcs.xml.dist`.

The regression test that's proposed in this issue is just that, testing regressions in existing rules.
I personally see no part-to-play for Coder to test new rules on Drupal core, but n=1, so open for suggestions on this one.

2023-07-17 08:11 UTC, jonathan1055 commented
Yes I'm totally with you on all that. I didn't mean to sound like I was taking anything away from your work - this is a superb addition to Coder's reliability and integrity.

2023-07-17 08:14 UTC, Boegie commented
Oh, I wasn't offended/whatever in any way/shape/form, nor do I oppose the opinion coder should test for failures on new rules.
_Blantatly playing my non-native-language card_

2023-07-17 15:04 UTC, klausi requested changes
Thanks, can we simplify this to be part of the normal PHP 8.2 test run?

2023-07-17 15:04 UTC, klausi commented on .github/workflows/testing.yml
> +          git clone https://git.drupalcode.org/project/drupal.git
we should use the github git mirror for drupal core for better speed. We should also use the checkout action.

Or is that not good because we don't have a good default git branch on github?

2023-07-17 15:04 UTC, klausi commented on .github/workflows/testing.yml
> +      - name: "Install Drupal core dependencies"
we don't need the drupal core dependencies at all, we just want to check the code of drupal core.

I'm thinking if we can integrate this whole job into the PHP 8.2 testing run further above? Like we do with PHPStan.

We clone Drupal core and run the local phpcs with drupal core's phpcs config. That should be all that is needed?

2023-07-17 15:12 UTC, Boegie commented on .github/workflows/testing.yml
> +      - name: "Install Drupal core dependencies"
> I'm thinking if we can integrate this whole job into the PHP 8.2 testing run further above? Like we do with PHPStan.

Wouldn't that clash with the the important green icon?
Wouldn't we be able to distinguish a fail in coder's code and a regression on core?

Anyway, this issue is getting way to complicated for lil ol' me, so I won't be persuing any chances.

2023-07-17 15:46 UTC, klausi commented on .github/workflows/testing.yml
> +      - name: "Install Drupal core dependencies"
Well, this pull request already does interfere with the important green icon as you demonstrated if I understand it correctly? Which is fine - if there is a regression in Drupal core we should know about it. Then there is a small chance that it is a false positive and we have to modify this Github action to work around it - which we also accept.

If we have different steps in the action we can see where it failed - either at Coders tests or at the Drupal core regression test.

No worries about the complication, anybody else can pick this up and we continue at a later point. Thanks for the contribution, nice demo in any case!

2023-07-18 11:30 UTC, closed without merging

2023-07-19 08:57 UTC, jonathan1055 commented on .github/workflows/testing.yml
> +      - name: "Install Drupal core dependencies"
??? what happened? This was going so well. I thought we were all in agreement (mostly) and that this was nearing being merged. It was such a good addition to the Coder's stability.

2023-07-19 10:41 UTC, Boegie commented on .github/workflows/testing.yml
> +      - name: "Install Drupal core dependencies"
Not much happenned, I assume?

There's a demo, things can be changed in the code, just not by me, important green icons is something beyond my comprehension/paygrade :)

2023-10-07 11:51 UTC, klausi commented
Continuing this work now in #211